=== 04lex/alex-workspace/LINK Academy/Service Application Development/Lesson 1/people.dtd
<!ELEMENT people (foaf:Person+, ruleaza)>
<!ATTLIST people xmlns:foaf %URI; #IMPLIED>
<!ELEMENT foaf:Person (foaf:name, alive)>
<!ELEMENT foaf:name (firstName, lastName)>
<!ELEMENT alive (#PCDATA)>
<!ATTLIST alive isAlive CDATA #REQUIRED>

<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT ruleaza (#PCDATA)>

=== 04lex/alex-workspace/LINK Academy/Service Application Development/Lesson 1/people.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE people SYSTEM "people.dtd">

<people xmlns:foaf="http://xmlns.com/foaf/0.1">
    <foaf:Person>
        <foaf:name>
            <firstName>Vasile</firstName>
            <lastName>Popescu</lastName>
        </foaf:name>
        <alive isAlive="true"/> <!--Self-closing tag-->
    </foaf:Person>
    <foaf:Person>
        <foaf:name>
            <firstName>Adri&lt;an</firstName>
            <lastName>O&apos;Dumitrascu</lastName>
        </foaf:name>
        <alive isAlive="true"/>
    </foaf:Person>
    <ruleaza>
        <![CDATA[ 
        <script>
            alert('Salut!');
        </script
        <script>
            console.log('Salut!');
        </script>
        ]]>
    </ruleaza>
</people>
